# Copyright (c) 2024 FORCERA, LDA
# 
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
# 
# SPDX-License-Identifier: EPL-2.0

services:
  
  framework:
    build: ./framework
    environment:
      - DISPLAY=unix$DISPLAY
      - QT_X11_NO_MITHSM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

networks:
  default:
    driver: bridge